# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/parsa/Downloads/RayTrace/RayTrace_Files

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/parsa/Downloads/RayTrace/RayTrace_Files/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/parsa/Downloads/RayTrace/RayTrace_Files/build/CMakeFiles /Users/parsa/Downloads/RayTrace/RayTrace_Files/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/parsa/Downloads/RayTrace/RayTrace_Files/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 04_RayTrace

# Build rule for target.
04_RayTrace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 04_RayTrace
.PHONY : 04_RayTrace

# fast build rule for target.
04_RayTrace/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/build
.PHONY : 04_RayTrace/fast

Camera.o: Camera.cpp.o
.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

Intersection.o: Intersection.cpp.o
.PHONY : Intersection.o

# target to build an object file
Intersection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Intersection.cpp.o
.PHONY : Intersection.cpp.o

Intersection.i: Intersection.cpp.i
.PHONY : Intersection.i

# target to preprocess a source file
Intersection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Intersection.cpp.i
.PHONY : Intersection.cpp.i

Intersection.s: Intersection.cpp.s
.PHONY : Intersection.s

# target to generate assembly for a file
Intersection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Intersection.cpp.s
.PHONY : Intersection.cpp.s

Material.o: Material.cpp.o
.PHONY : Material.o

# target to build an object file
Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Material.cpp.o
.PHONY : Material.cpp.o

Material.i: Material.cpp.i
.PHONY : Material.i

# target to preprocess a source file
Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Material.cpp.i
.PHONY : Material.cpp.i

Material.s: Material.cpp.s
.PHONY : Material.s

# target to generate assembly for a file
Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Material.cpp.s
.PHONY : Material.cpp.s

Ray.o: Ray.cpp.o
.PHONY : Ray.o

# target to build an object file
Ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Ray.cpp.o
.PHONY : Ray.cpp.o

Ray.i: Ray.cpp.i
.PHONY : Ray.i

# target to preprocess a source file
Ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Ray.cpp.i
.PHONY : Ray.cpp.i

Ray.s: Ray.cpp.s
.PHONY : Ray.s

# target to generate assembly for a file
Ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Ray.cpp.s
.PHONY : Ray.cpp.s

Scene.o: Scene.cpp.o
.PHONY : Scene.o

# target to build an object file
Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Scene.cpp.o
.PHONY : Scene.cpp.o

Scene.i: Scene.cpp.i
.PHONY : Scene.i

# target to preprocess a source file
Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Scene.cpp.i
.PHONY : Scene.cpp.i

Scene.s: Scene.cpp.s
.PHONY : Scene.s

# target to generate assembly for a file
Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Scene.cpp.s
.PHONY : Scene.cpp.s

Screen.o: Screen.cpp.o
.PHONY : Screen.o

# target to build an object file
Screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Screen.cpp.o
.PHONY : Screen.cpp.o

Screen.i: Screen.cpp.i
.PHONY : Screen.i

# target to preprocess a source file
Screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Screen.cpp.i
.PHONY : Screen.cpp.i

Screen.s: Screen.cpp.s
.PHONY : Screen.s

# target to generate assembly for a file
Screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Screen.cpp.s
.PHONY : Screen.cpp.s

Sphere.o: Sphere.cpp.o
.PHONY : Sphere.o

# target to build an object file
Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Sphere.cpp.o
.PHONY : Sphere.cpp.o

Sphere.i: Sphere.cpp.i
.PHONY : Sphere.i

# target to preprocess a source file
Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Sphere.cpp.i
.PHONY : Sphere.cpp.i

Sphere.s: Sphere.cpp.s
.PHONY : Sphere.s

# target to generate assembly for a file
Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Sphere.cpp.s
.PHONY : Sphere.cpp.s

Vector3.o: Vector3.cpp.o
.PHONY : Vector3.o

# target to build an object file
Vector3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Vector3.cpp.o
.PHONY : Vector3.cpp.o

Vector3.i: Vector3.cpp.i
.PHONY : Vector3.i

# target to preprocess a source file
Vector3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Vector3.cpp.i
.PHONY : Vector3.cpp.i

Vector3.s: Vector3.cpp.s
.PHONY : Vector3.s

# target to generate assembly for a file
Vector3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/Vector3.cpp.s
.PHONY : Vector3.cpp.s

YourRayTracer.o: YourRayTracer.cpp.o
.PHONY : YourRayTracer.o

# target to build an object file
YourRayTracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/YourRayTracer.cpp.o
.PHONY : YourRayTracer.cpp.o

YourRayTracer.i: YourRayTracer.cpp.i
.PHONY : YourRayTracer.i

# target to preprocess a source file
YourRayTracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/YourRayTracer.cpp.i
.PHONY : YourRayTracer.cpp.i

YourRayTracer.s: YourRayTracer.cpp.s
.PHONY : YourRayTracer.s

# target to generate assembly for a file
YourRayTracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/YourRayTracer.cpp.s
.PHONY : YourRayTracer.cpp.s

lodepng.o: lodepng.cpp.o
.PHONY : lodepng.o

# target to build an object file
lodepng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/lodepng.cpp.o
.PHONY : lodepng.cpp.o

lodepng.i: lodepng.cpp.i
.PHONY : lodepng.i

# target to preprocess a source file
lodepng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/lodepng.cpp.i
.PHONY : lodepng.cpp.i

lodepng.s: lodepng.cpp.s
.PHONY : lodepng.s

# target to generate assembly for a file
lodepng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/lodepng.cpp.s
.PHONY : lodepng.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/04_RayTrace.dir/build.make CMakeFiles/04_RayTrace.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 04_RayTrace"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... Intersection.o"
	@echo "... Intersection.i"
	@echo "... Intersection.s"
	@echo "... Material.o"
	@echo "... Material.i"
	@echo "... Material.s"
	@echo "... Ray.o"
	@echo "... Ray.i"
	@echo "... Ray.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... Screen.o"
	@echo "... Screen.i"
	@echo "... Screen.s"
	@echo "... Sphere.o"
	@echo "... Sphere.i"
	@echo "... Sphere.s"
	@echo "... Vector3.o"
	@echo "... Vector3.i"
	@echo "... Vector3.s"
	@echo "... YourRayTracer.o"
	@echo "... YourRayTracer.i"
	@echo "... YourRayTracer.s"
	@echo "... lodepng.o"
	@echo "... lodepng.i"
	@echo "... lodepng.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

